# Generated by Django 3.1.3 on 2020-12-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('year', models.CharField(max_length=5)),
                ('ratings', models.CharField(max_length=3)),
                ('metascore', models.CharField(max_length=5)),
                ('votes', models.CharField(max_length=10)),
                ('gross_income', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'movies',
                'ordering': ['year'],
            },
        ),
    ]
