# Generated by Django 3.1.3 on 2020-12-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_viz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night_period', models.CharField(max_length=15)),
                ('day_period', models.CharField(max_length=15)),
                ('night_temp', models.CharField(max_length=5)),
                ('day_temp', models.CharField(max_length=5)),
                ('night_humidity', models.CharField(max_length=5)),
                ('day_humidity', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'weather',
            },
        ),
    ]
