# Generated by Django 3.1.4 on 2020-12-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_viz', '0002_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceLazada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=120)),
                ('price', models.CharField(default='0', max_length=10)),
            ],
            options={
                'db_table': 'lazada',
            },
        ),
        migrations.CreateModel(
            name='EcommerceShopee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=120)),
                ('price', models.CharField(default='0', max_length=10)),
            ],
            options={
                'db_table': 'shopee',
            },
        ),
    ]
